# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ORIOSSummary' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

    pod 'SDWebImage', '~> 4.4.6'
    pod 'CYLTabBarController'
    pod 'MJRefresh'
    pod 'MBProgressHUD', '~> 0.9'
    
  # Pods for ORIOSSummary

  target 'ORIOSSummaryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ORIOSSummaryUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
