platform :ios, ‘7.0‘
target "ProjectDemo" do

pod 'AFNetworking', '~>2.6.0'
pod 'Masonry','~>0.6.1'
pod 'SDWebImage', '~> 3.7.5'
pod 'IQKeyboardManager', '~> 3.3.7'  #兼容IOS7
pod 'CYLTabBarController'
pod 'MWPhotoBrowser'

pod 'BaiduMapKit’,’2.10.2’
pod 'JSPatch'#热更新
pod 'LBXScan','~> 1.1.1'#二维码扫描

pod ‘UMengUShare/UI’ #友盟
pod ‘UMengUShare/Social/WeChat'
pod ‘UMengUShare/Social/QQ'
pod ‘UMengUShare/Social/Sina'

pod 'UMengAnalytics-NO-IDFA'#友盟统计无IDFA版SDK

pod 'GTSDK'  #个推SDK

pod 'CocoaLumberjack', '~> 2.0.0-rc'#日志记录需要导入
pod 'FLEX', '~> 2.0', :configurations => ['Debug']
pod 'JSONModel', '~> 1.0.1'

pod 'ActionSheetPicker-3.0'
pod 'MBProgressHUD', '~> 0.9'
pod 'M13ProgressSuite', '~> 1.2.7'
pod 'ReactiveCocoa', '~> 2.5'
pod 'YYText'
pod 'XAspect'
pod 'WebViewJavascriptBridge', '~> 5.0'

end
